conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:item_pk>/', views.new_conversation, name='new'),
]

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('privacy/', views.privacy, name='privacy'),
    path('terms/', views.terms, name='terms'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', views.logout_view,name='logout'),
    path('checkout/success/', views.checkout_success, name='checkout_success'),
    path('checkout/cancel/', views.checkout_cancel, name='checkout_cancel'),

]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

item/urls.py
from django.urls import path

from . import views


app_name = 'item'

urlpatterns = [
    path('', views.items, name='items'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>', views.add_to_cart, name='add_to_cart'),
    path('view-cart/', views.view_cart, name='view_cart'),
    path('<int:pk>/remove-from-cart/', views.remove_from_cart, name='remove_from_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('checkout/success/', views.checkout_success, name='checkout_success'),

    path('checkout/cancel/', views.checkout_cancel, name='checkout_cancel'),

]

puddle/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import logout


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

core/views.py
from django.contrib.auth import logout
from django.shortcuts import render, redirect

from item.models import Category, Item

from .forms import SignupForm


def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()

    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items,
    })


def contact(request):
    return render(request, 'core/contact.html')


def about(request):
    return render(request, 'core/about.html')


def privacy(request):
    return render(request, 'core/privacy.html')


def terms(request):
    return render(request, 'core/terms.html')


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {
        'form': form
    })


def logout_view(request):
    # Log the user out
    logout(request)

    return redirect('/login')



def checkout_success(request):
    return render(request, 'checkout_success.html')


def checkout_cancel(request):
    return render(request, 'checkout_cancel.html')

# Other views...

core/templates/core/about.html
{% extends 'core/base.html' %}

{% block title %}About us{% endblock %}

{% block content %}
    <h1 class="text-center bg-green-600">This is the about us page page</h1>
    <p>
    Welcome to Mobile Electronic Device marketplace system  MarketplaceApp, where a world of possibilities unfolds at your fingertips. Our online marketplace is more than just a platform; it's a vibrant community connecting buyers and sellers in a seamless, dynamic environment. At Online marketplaceApp, we believe in redefining the online shopping experience. We've curated a diverse range of products and services to cater to every need and desire. Whether you're searching for unique handmade crafts, cutting-edge tech gadgets, or exclusive services, we've got you covered. Our commitment goes beyond transactions; it's about fostering connections. We take pride in providing a user-friendly interface that encourages meaningful interactions and cultivates a sense of community. Join a marketplace where individuals and businesses converge to explore, discover, and thrive. Transparency and trust are the cornerstones of Online marketplaceApp. We prioritize the security of your transactions and ensure that your personal information is handled with the utmost care. Our dedicated support team is always ready to assist you, ensuring a smooth and enjoyable shopping experience. Discover a marketplace that evolves with you. Online marketplaceApp is not just a destination; it's a journey of endless possibilities. Start exploring today, and let the adventure unfold. Welcome to Online marketplaceApp – Your World, Your Marketplace.
    </p>
{% endblock %}

core/templates/core/base.html
<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>

        <title>{% block title %}{% endblock %} | Brianshopify</title>
    </head>

    <body>
        <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
            <a href="/" class="text-xl font-semi-bold">Mobile electronics app</a><br><br>

            <div class="space-x-6">

{#                <a href="{% url 'item:new' %}" class="px-6 py-3 text-lg font-semi-bold bg-teal-500 text-white rounded-xl hover:bg-teal-700">New item</a>#}
{#                <a href="{% url 'item:items' %}" class="px-6 py-3 text-lg font-semi-bold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Browse</a>#}
{#                <a href="{% url 'item:view_cart' %}" class="px-6 py-3 text-lg font-semi-bold bg-teal-500 text-white rounded-xl hover:bg-teal-700">View Cart</a>#}
{#                <a href="{% url 'core:logout' %}" class="px-6 py-3 text-lg font-semi-bold bg-green-500 text-white rounded-xl hover:bg-gray-700">Log Out</a>#}
{#                <a href="{% url 'item:add_to_cart' %}" class="inline-block mt-6 px-6 py-3 text-lg font-semi-bold bg-blue-500 text-white rounded-xl hover:bg-blue-700">Add To Cart</a>#}

                {% if request.user.is_authenticated %}
                    <a href="{% url 'item:new' %}" class="px-6 py-3 text-lg font-semi-bold bg-teal-500 text-white rounded-xl hover:bg-teal-700">New item</a>
                    <a href="{% url 'item:items' %}" class="px-6 py-3 text-lg font-semi-bold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Browse</a>
                    <a href="{% url 'item:view_cart' %}" class="px-6 py-3 text-lg font-semi-bold bg-teal-500 text-white rounded-xl hover:bg-teal-700">View Cart</a>
                    <a href="{% url 'conversation:inbox' %}" class="px-6 py-3 text-lg font-semi-bold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Inbox</a>
                    <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semi-bold bg-yellow-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>
                    <a href="{% url 'core:logout' %}" class="px-6 py-3 text-lg font-semi-bold bg-green-500 text-white rounded-xl hover:bg-gray-700">Log Out</a>
                {% else %}
                    <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semi-bold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
                    <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semi-bold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
                    <a href="{% url 'core:logout' %}" class="px-6 py-3 text-lg font-semi-bold bg-green-500 text-white rounded-xl hover:bg-gray-700">Log Out</a>
                {% endif %}
            </div>
        </nav>

        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>

        <footer class="py-6 px-2 flex justify-between bg-gray-800">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semi-bold text-gray-400">About</h3>

                <p class="text-lg text-gray-500">Welcome to Online MarketplaceApp, where a world of possibilities unfolds at your fingertips. Our online marketplace is more than just a platform; it's a vibrant community connecting buyers and sellers in a seamless, dynamic environment.
.</p>
            </div>

            <div class="w-1/3">
                <h3 class="mb-5 font-semi-bold text-gray-400">Menu</h3>

                <ul class="space-y-2">
                    <li><a href="{% url 'core:about' %}" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                    <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                    <li><a href="{% url 'core:privacy' %}" class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</a></li>
                    <li><a href="{% url 'core:terms' %}" class="text-lg text-teal-500 hover:text-teal-700">Term of use</a></li>
                </ul>
            </div>
        </footer>
    </body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
    <h1 class="text-center bg-green-600">The contact page</h1>
       <p class="bg-blue-700">
    Thank you for choosing Online MarketplaceApp ! We value your feedback, inquiries, and concerns. Here's how you can get in touch with us:

Customer Support:
If you need assistance with an order, have a question, or simply want to share your experience, our dedicated customer support team is here to help. Reach out via email at briankimita21@gmail.com or use the contact form below.

Business Inquiries:
For partnership opportunities, vendor collaborations, or any business-related queries, please contact our business development team at partnerships@yourmarketplace.com.

Technical Support:
Encountering technical issues? Our tech support experts are ready to assist you. Drop them an email at techsupport21@onlinemaarketplaceapp.com, and we'll work to resolve the issue promptly.

Media and Press:
For media inquiries, interviews, or press-related matters, please contact our media relations team at media@onlinemaarketplaceapp.com.

General Inquiries:
Have a general question or comment? Feel free to reach us at info@onlinemaarketplaceapp.com, and we'll get back to you as soon as possible.

Visit Us:
If you prefer face-to-face interaction, our office is located at onlinemaarketplaceapp HQ, Street Address 20-10103, Nairobi, Kenya. Please note that visits are by appointment only.

We appreciate your trust in onlinemaarketplaceapp, and we look forward to hearing from you. Your satisfaction is our priority, and we're committed to making your experience with us exceptional.

    </p>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Newest items</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">

                        <div>
                            <img src="{{ item.image.url }}" class="rounded-t-xl" alt="#">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">Price: {{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
                <div>
                    <a href="#">
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ category.name }}</h2>
                            <p class="text-gray-500">{{ category.items.count }} items</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Log in</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}

core/templates/core/logout.html
{% extends 'core/base.html' %}
{% block content %}
    <a href="{% url 'logout' %}">Logout</a>
{% endblock %}

core/templates/core/privacy.html
{% extends 'core/base.html' %}

{% block title %}About us{% endblock %}

{% block content %}
    <h1 class="text-center bg-blue-600">This is the privacy policy  page</h1>
<p class="bg-green-500">
At Online marketplace, we are committed to safeguarding your privacy and ensuring the security of your personal information. This Privacy Policy outlines how we collect, use, and protect the data you provide to us.

Information Collection:

We collect personal information, including but not limited to, your name, email address, shipping address, and payment details when you register on our platform or make a purchase.
Use of Information:

Your information is used to process transactions, personalize your experience, and improve our services.
We may use your email address to send you updates, promotions, and important information. You can opt-out of these communications at any time.
Data Security:

We implement industry-standard security measures to protect your personal information from unauthorized access, disclosure, alteration, and destruction.
Cookies:

We use cookies to enhance your browsing experience. You can disable cookies in your browser settings, but this may affect certain features of our platform.
Third-Party Disclosure:

We do not sell, trade, or otherwise transfer your personal information to outside parties. Trusted third parties who assist us in operating our platform are required to keep your information confidential.
User Control:

You have the right to access, correct, or delete your personal information. You can manage your preferences through your account settings or by contacting our customer support.
</p>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Confirm password</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}

core/templates/core/terms.html
{% extends 'core/base.html' %}

{% block title %}About us{% endblock %}

{% block content %}
    <h1 class="text-center bg-green-600">This is the terms of use page</h1>
    <p class="bg-red-300">
    By using Online Marketplace, you agree to the following terms:

Account Responsibility:

You are responsible for maintaining the confidentiality of your account information, including your password. Any activities under your account are your responsibility.
Prohibited Activities:

Users must not engage in any unlawful or prohibited activities while using our platform. This includes, but is not limited to, fraud, harassment, and violation of intellectual property rights.
Product Listings:

Sellers are responsible for the accuracy and legality of their product listings. Prohibited items include illegal goods, counterfeit items, and those infringing on intellectual property rights.
Payment and Transactions:

Transactions on our platform are secure. Users agree to pay the specified amount for products or services purchased and understand that all sales are final.
Intellectual Property:

Users must respect the intellectual property rights of others. Any unauthorized use of trademarks, copyrights, or other proprietary information is strictly prohibited.
Termination of Account:

[Your Marketplace Name] reserves the right to terminate or suspend accounts that violate our terms of use or for any other reason deemed necessary.
By using [Your Marketplace Name], you acknowledge that you have read, understood, and agree to abide by our Privacy Policy and Terms of Use. We may update these policies, and it is your responsibility to review them periodically for changes.
    </p>
{% endblock %}